### PR TITLE
Make it run on gentoo and archlinux

### PR DESCRIPTION
**Pull request by guimaluf**
Unify gentoo and arch in the same task

Add system-auth gentoo file

### CODE REVIEW

**Comment by martbhell** [comment]
Thanks for the PR!

**Comment by martbhell** [comment]
I spent some time trying to enable testing of gentoo in a branch in this repo but I'm stumbling on how to enable USE flags :) 

Do you know how to ? Also there's many USE= in that output. Do you have an idea how to easily get a list of all the USE flags needed for a package and all its dependencies?

p.s. I've never used Gentoo

https://travis-ci.org/CSC-IT-Center-for-Science/ansible-role-sssd/jobs/175010740

**Comment by guimaluf** [comment]
You're right. sssd requires lots of use flags and masks.
I would run 

```
emerge --autounmask-write sssd
etc-update --automode -5
emerge sssd
```

That way, emerge automagically sets the dependencies flags for sssd

Hope it work!

**Comment by martbhell** [comment]
If I run those commands - do I use those to install sssd and not ansible? If so it's not really a good fix.
Anyway, I tried to add those to the .travis file and the ansible command still doesn't work :/
Is the role working for you?

**Comment by guimaluf** [comment]
It use to work. I'll test against a clean docker gentoo container and check what need to be fixed.

**Pull request merged**
